### ISSUE TITLE
Publish the latest version of Jupyter extension

### ISSUE THREAD

**Issue by aminelajmi** [open-vsx/publish-extensions#698]
Could you please upgrade the Jupyter (ms-toolsai.jupyter) extension to `v2023.7.1002162226` ?

Thank you.

**Comment by filiptronicek** [comment]
Hello there @aminelajmi 👋,
thanks for the issue and bringing this to our attention. It seems the dependency installation process for the extension got changed. I've got a fix ready.

**Comment by filiptronicek** [comment]
I now published a new version of Jupyter. Hope it helps!

**Comment by aminelajmi** [comment]
May be I missed something, but I still see version 2023.04 as the latest, should I look elsewhere ?

<img width="1145" alt="Capture d’écran 2023-08-17 à 17 00 10" src="https://github.com/open-vsx/publish-extensions/assets/81257433/274b3480-b1b1-43f2-968f-357ee7951ac2">

**Comment by filiptronicek** [comment]
Seems like something's off with Open VSX and the version did not properly publish. I have asked the team responsible for help.

**Comment by aminelajmi** [comment]
Any updates on this? Thanks

**Comment by filiptronicek** [comment]
@aminelajmi we have partially unblocked this issue now and I've made [`2023.7.100`](https://open-vsx.org/extension/ms-toolsai/jupyter/2023.7.100) available. I hope that we can get later versions working automatically again.

**Comment by aminelajmi** [comment]
Thanks a lot @filiptronicek
